name: dotnet package
on:
  push:
    branches:
      - feature/mq

jobs:
  build-node:
    name: Build-Node
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: |
          apt-get -y update && apt-get -y install protobuf-compiler
          dotnet --version
          dotnet publish AElf.sln /p:NoBuild=false --configuration Release -o /build/node
          docker build -t node -f .github/workflows/Dockerfile .
          docker tag node ienyan/aelf-node-mq
          docker login -u ${{ secrets.DOCKER_ENYUAN_USER }} -p ${{ secrets.DOCKER_TEST_ENYUAN_PASSWD }}
          docker push ienyan/aelf-node-mq
